### ISSUE TITLE
Not sure where to start discourse on this, here works I guess

### ISSUE THREAD

**Issue by andyleejordan** [sdboyer/dear_github_can_i_go_home_now#2]
I don't think I understand what it is that has you so you upset you feel the need to "game the system" like this. I read "Why GitHub is not your CV" when it popped up in my RSS feeds not too long ago, and although there are some good points, I for the most part disagreed. I disagree that there is a problem. Being a student, and therefore recently in the job market, I failed to see any "requirement" by employers to have an active GitHub. If you have one, it's just a bonus way to show potential employers your own projects.

If someone's commits to GitHub are solely because they feel the need to "look good" to employers, that's their own fault. Neglecting one's duties to code is just as bad as neglecting it for any other reason, and is a problem with the person, not some open-source project hosting website. GitHub's "contributions" graph isn't there to measure one's self-worth, it's a fun statistic, no more. Personally, I've been more dedicated than I should be to one of current school courses, and have somehow racked up a 40-something day streak. Yes, it makes me feel good, but what game score doesn't? I'm pretty sure that's just human psychology. Whereas when I was working full-time this summer, my contributions are sparse. But this isn't a problem, and my CV isn't lacking for it. Instead of GitHub, I held a full-time software engineering internship, and in interviews had more project experience than I needed to get by.

The only problem with a "lack of contributions" is if it also corresponds to a lack of effort anywhere. If someone is unemployed and not working on anything whatsoever, then yes, that's going to look bad to employers. _As it should._

On the other hand, this "generate self-worth" crack is just that, an attempt to boycott a problem that simply doesn't exist. If the only way someone can feel good about themselves is to game a system and give themselves the high score, go for it, but have fun explaining it to employers; I don't think they're going to find it as funny as I do.

P.S. Please don't take this the wrong way, I can see where you're coming from, but a) don't think the problem is as bad as it's been made out to be, and b) this isn't the solution. The solution is a well-formed portfolio, open-source or not.

**Comment by JaimeLynSchatz** [comment]
I'm speaking third-hand here (I'm not yet a professional dev), but from what I'm hearing, many (not all) employers are beginning to give as much weight (if not more) to one's public GitHub activity than to a self-curated portfolio. "Gaming the system" is one way to demonstrate the silliness in that. (Extra parenthesis added to demonstrate my own over-reliance on parenthetical references.) ;)

**Comment by sdboyer** [comment]
ahhh! i totally had my notifications turned off for this thing. lol, i'm clearly a pro.

@andschwa so the honest truth, snark aside, is that i'm not actually sure how i feel about this thing here that i've written, when all's said and done. the one thing that is clear is, to quote you with respect to the streaks, "Yes, it makes me feel good, but what game score doesn't?" the fact that Github puts the number out there establishes the streak as a "good thing," thus incentivizing the behavior.

so, is that "good" or "bad"? well, it's not black and white. one friend pointed out that he likes the spike of guilt he gets when the streak is low or the graph is too white, because it encourages him to go back to some of his open source work. and personally, i'm inclined to agree.

but those articles also made the really good point that people are increasingly looking at Github profiles as a rather simplistic indicator of whether or not someone is a worthwhile job candidate. such "looking" no doubt goes beyond a simplistic "what color is the graph," but that's fine, because [protests are generally symbolic, not literal, acts](http://www.salsa.net/peace/conv/8weekconv6-3.html). it's an analogy - in the same way that my contributions graph and streak are now not necessarily representative of my Github profile as a whole, someone's Github profile as a whole is not necessarily representative of their quality as a job candidate. of course, i don't expect anyone to _consciously_ think that; i'm satisfied in the belief that simply putting something out there (a solid green graph) that gives someone pause might be enough to reinforce a subconscious thought: "Github can lie to me."

personally, i don't think i'd really want to work anywhere that would consider my doing this a mark _against_ me. but who knows, maybe it will make me miss out on something i would have really loved. 

i also don't know if this is really a protest. but i do know that that if you protest without putting skin in the game, it means a hell of a lot less.

**Comment by rabcyr** [comment]
everyone can protest together!
http://tpm.laurelmail.net
https://github.com/twitchplaysmeritocracy

**Comment by andyleejordan** [comment]
@sdboyer I'm about four years late, and a lot of my opinions have changed.

> personally, i don't think i'd really want to work anywhere that would consider my doing this a mark against me.

I completely agree. And I see the value in protesting the grotesque hiring practices in our industry (and others!). I think this is a cool project, and effectively protests such practices, even if in a symbolic way. Nowadays companies are sending candidates home with literal _days_ of homework!

Personally, I think everyone has the right to fair employment (considering it's a necessity in this particular economic system in order to have such fundamental rights as food, shelter, health care, and the like).

Anyway, thanks all for the discussion. I'm closing this now after going through my open issues. 😄

**Comment by sdboyer** [comment]
❤❤❤❤❤❤❤❤❤❤❤
